### PR TITLE
Trying to give warning for no space for ship issue

### PR DESCRIPTION
**Pull request by Imzogelmo**
This is an attempt to give some meaningful indication when ships cannot deploy where no space exists. Issue #254

### CODE REVIEW

**Comment by dmcbride** [comment]
For future reference, having the baseline branch be "develop" would make this easier :)

**Comment by lemming552** [comment]
I think this is a good item to do, though I was talking to icy about something extra with thuds...  Bleeders have another path, but this would still work along with Tower's enhancement of free spaces.

**Comment by lemming552** [comment]
Clicked on the wrong window.   (And yes, branching off develop would be better, though I think your stuff can be brought in without too much issue, but it will have to be examined closer.)

**Comment by Imzogelmo** [comment]
Second one corrects an incorrect variable name. Silly me, copied and pasted.

**Comment by Imzogelmo** [comment]
changed name to type to better fit with the message

**Pull request closed without merging**
